### ISSUE TITLE
Consider a Slack theme

### ISSUE THREAD

**Issue by fpaguiar** [will-stone/plastic#165]
Recently found the VSCode theme and I'm loving it! Thank you for making this theme, colors are just beatiful!

Not sure if this is the right place, but can I make a request? Would you be open to create a theme for Slack sidebar?

I managed to create one myself based on the colour palette from the website, but would like to ask if you would be willing to provide an official version in the website.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/22917135/113794784-f4f68680-9710-11eb-83a4-1099d0f61e83.png">

(you can use [this link](https://slackthemes.net/#/custom#21252B,121016,61afef,0d1117,181A1F,C6CCD7,98c379,d74e42,0D1117,c6ccd7) to see the preview as well)

Thank you!

**Comment by will-stone** [comment]
Thanks! Definitely 😊 I’m still sorting out a few things with the website, like dynamically pulling in details from the theme directories, and whether or not we do bright ANSI colours, but once that’s done I hope to add a lot more.

I also need to write a “spec” sheet. Because the idea behind Plastic isn’t that one (IDE) theme matches another exactly token-for-token. It’s that the configuration remains simple and (relatively) language agnostic. This can be seen in the VSCode theme’s scopes at the bottom of the theme src file. I’ll formalise this when I get a chance.

**Comment by will-stone** [comment]
@fpaguiar Been having a play. It's a shame Slack don't allow for more themed items, but here's my attempt, what do you reckon?

https://slackthemes.net/#/custom#21252B,0B161E,61AFEF,0D1117,2E3239,C6CCD7,98C379,E06C75,181A1F,FFFFFF

**Comment by will-stone** [comment]
Actually, I think I prefer the Shuttle Gray highlight as the blue clashes with the red: https://slackthemes.net/#/custom#21252B,0B161E,5F6672,FFFFFF,2E3239,C6CCD7,98C379,E06C75,181A1F,FFFFFF

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/654103/113993374-540ce600-984c-11eb-9345-1c0e52bfc1bf.png">

**Comment by fpaguiar** [comment]
Looking beautiful, Will! Thanks a lot!!

Sorry for the delay btw. The email notification got snowed under a bunch of other stuff..

**Comment by will-stone** [comment]
No worries 😎
