### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by GavinRay97** [will-stone/plastic#170]
I'd been using the same theme for the majority of my career.

Every year or so I would try out some themes trying to spice it up, sometimes I'd find one I liked a bit + would use for a few weeks but I always went back to ole' trusty.

Until Plastic. I tried Plastic when it was in V1 and thought it was solid (the de-prioritized punctuation option was really clever and something I wish more themes would offer) but decided it wasn't for me.

Then maybe 6-7 months ago I tried it again, noticing a V2 had been published, and it's the most "perfect" theme I've ever found.

Thank you for making it <3

**Comment by will-stone** [comment]
That’s very kind of you. Out of interest, what was your “ole’ trusty” theme?

**Comment by GavinRay97** [comment]
Atom One Dark, I started using it back when Atom was the "hot new thing" and just really loved it

**Comment by will-stone** [comment]
Ah me too 🙂 One Dark Pro is how Plastic started: I contributed a bunch of commits to the project to style bits of the UI. I even designed the logo. Then, once I’d learnt my way around the structure of making a theme, I thought I’d prefer something darker, and less opinionated. One Dark Pro is a great theme but must constantly try to keep in sync with Atom’s One Dark. I wanted something that wasn’t bound by that constraint. If you compare the two’s source code, you can see Plastic only styles syntax at a high level, rather than being specific with certain colours for certain languages 🤓

**Comment by GavinRay97** [comment]
Oh that is actually a really cool piece of history, what a coincidence -- ha!
