### ISSUE TITLE
JS object in shorthand syntax gets variable color highlighting

### ISSUE THREAD

**Issue by bittuamar** [will-stone/plastic#26]
When using shorthand syntax, JS object gets a mix of text and variable colors. Is this expected ? 

![screen shot 2018-06-15 at 5 55 15 am](https://user-images.githubusercontent.com/3953467/41462553-3dd63302-7061-11e8-9725-c47aa5f719ba.png)

In the screenshot above, "schema" and "models" are of the color Iron(#D2D6db). Technically they are variables of the same name but would it be better if they were the same as text color?

**Comment by will-stone** [comment]
Hi, this is the first issue you have logged against Plastic. You didn't read the article in the issue template, did you?

That aside. No. They use the variable colour because they are variables. It helps distinguish them nicely from those that are just text:

![core 2018-06-15 11-19-51](https://user-images.githubusercontent.com/654103/41463405-4173b5f2-708e-11e8-9d99-a59ffe5e82c8.png)

Thank you for using Plastic. Despite my stance on politeness, don't be afraid to log more issues, just remember the project is provided for free and a thank-you goes a long way 🙂

**Comment by bittuamar** [comment]
@will-stone You are right I actually didn't read that article. I'm sorry about that and it was never my intention to come off as rude. I won't let this happen again. And thank you for creating this theme and keeping it free.

**Comment by will-stone** [comment]
No worries. Again, thanks for the feedback. I'm in the process of making a (hopefully) really easy Plastic compiler where you'll be able to build your own theme. Watch this space.
